config/routes.rb
Juicevault::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :juices, :only => [:index, :create, :show, :update, :destroy]
      resources :users
      devise_scope :user do
        post '/sign_in', :to => 'sessions#create'
        delete '/sign_out', :to => 'sessions#destroy'
      end
    end
  end

  resources :juices do
    put :favorite, on: :member
    resources :comments
  end

  resources :ratings

  resources :dashboard

  devise_for :users

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>JuiceVault<%= content_for?(:title) ? ' | ' + yield(:title) : "" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  </head>

  <body>
    <div class="sticky">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <% if user_signed_in? %>
              <h1><%= link_to '<i class=\'fa fa-tint green-drop\'></i> JuiceVault <small>(beta)</small>'.html_safe, dashboard_index_path %></h1>
            <% else %>
              <h1><%= link_to '<i class=\'fa fa-tint green-drop\'></i> JuiceVault <small>(beta)</small>'.html_safe, root_path %></h1>
            <% end %>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
        </ul>
        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <% if user_signed_in? %>
              <!-- <li class="has-form">
                <div class="row collapse">
                  <div class="small-9 large-8 columns">
                    <%= text_field_tag :search, params[:search], placeholder: "Search for a name, brand or category" %>
                  </div>
                  <div class="small-3 large-4 columns">
                    <%= submit_tag "Search", :name => nil, class: "button" %>
                  </div>
                </div>
              </li> -->
              <li><%= link_to 'Juices', juices_path %></li>
              <li><%= link_to 'Add Juice', new_juice_path %></li>
              <li class="has-dropdown">
                <%= link_to image_tag(avatar_url(current_user, 28), :alt => current_user.email, :class => 'avatar') + current_user.username, dashboard_index_path %>
                <ul class="dropdown">
                  <li><%= link_to 'Dashboard', dashboard_index_path %></li>
                  <li><%= link_to "Account Settings", edit_user_registration_path %></li>
                  <li><a href="http://juicevault.uservoice.com/" target="_blank">Support</a></li>
                  <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Juices', juices_path %></li>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <li><a href="http://juicevault.uservoice.com/" target="_blank">Support</a></li>
            <% end %>
          </ul>
        </section>
      </nav>
    </div>
    <div class="container">
      <div class="row">
        <div class="small-12 columns">
          <% if(notice) %>
            <div data-alert class="alert-box">
              <%= notice %>
              <a href="#" class="close">&times;</a>
            </div>
          <% end %>
          <% if(alert) %>
            <div data-alert class="alert-box warning">
              <%= alert %>
              <a href="#" class="close">&times;</a>
            </div>
          <% end %>
        </div>
      </div>

      <%= yield %>

    </div>
    <footer class="sitefooter">
      <nav class="top-bar">
        <section class="top-bar-section">
          <ul class="left">
            <li><a>&copy; 2014 JuiceVault</a></li>
          </ul>
          <ul class="right">
            <li><a href="http://juicevault.uservoice.com/" target="_blank">Support</a></li>
          </ul>
        </section>
      </nav>
    </footer>
    <%= javascript_include_tag "application" %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-48417724-1', 'myjuicevault.com');
      ga('send', 'pageview');

    </script>
  </body>
</html>